# Autogenerated file
onerror {
	quit -f -code 1
}
vmap -c
if [file exists sim_build/work] {vdel -lib sim_build/work -all}
vlib sim_build/work
vmap work sim_build/work
vcom -work work +acc ~/Project-sarvottam/Projects/RTL_Designs/rtl/building_blocks/*.vhd
vsim  -onfinish exit -t 1ps -foreign "cocotb_init /home/abisop-nvme/.local/lib/python3.10/site-packages/cocotb/libs/libcocotbfli_modelsim.so"   work.
onbreak resume
run -all
quit
